/* Generated by scripts/gen_edge_intercept_table.py - do not edit.
 *
 * An open-addressed table over the edge intercept addresses. The lookup
 * walks a short probe chain and stops at the first empty slot, which is
 * why it cannot answer false for a key the switches match - an empty slot
 * means the key was never placed. It is built from the same case lists the
 * switches use; a hit only skips the switches, which stay the authority.
 * The placement is chosen for the longest probe, and the generator
 * verifies every key is found again after placing it. */
#ifndef BLUEWAKE_EDGE_INTERCEPT_TABLE_H
#define BLUEWAKE_EDGE_INTERCEPT_TABLE_H

#include "core/cpu.h"

#define BLUEWAKE_EDGE_KEY_COUNT 55u
#define BLUEWAKE_EDGE_KEY_MULT 668265263u
#define BLUEWAKE_EDGE_KEY_SHIFT 24u
#define BLUEWAKE_EDGE_KEY_SLOTS 256u
static const u32 g_edge_keys[BLUEWAKE_EDGE_KEY_SLOTS] = {
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0x80120188u,
    0x8031D2E0u, 0x8031DAFCu, 0x8022F9FCu, 0u, 0u, 0u, 0u, 0u,
    0u, 0x8031F7C8u, 0u, 0u, 0u, 0x80230A14u, 0x81E01B88u, 0u,
    0x8031E5C8u, 0x8030FBCCu, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0x8031F984u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0x8031DD80u, 0u, 0u,
    0u, 0x8030F2B0u, 0x802315A8u, 0u, 0u, 0u, 0u, 0u,
    0x80303A50u, 0u, 0u, 0u, 0x802411F8u, 0u, 0u, 0x8015D80Cu,
    0x80240EE8u, 0x80322BC8u, 0u, 0u, 0u, 0u, 0x8031EA48u, 0x800D8DB8u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0x80241178u, 0x8031F69Cu, 0x8017E86Cu, 0u, 0u, 0x8017E798u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0x81E01BA4u, 0u, 0u, 0x81E000D4u, 0u, 0x8031CD50u, 0x8031E74Cu,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0x801DBA58u, 0u, 0x803193ACu, 0u, 0u, 0x8031D438u, 0u, 0x801DD960u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0x80308A9Cu, 0u, 0x80017FD8u,
    0u, 0u, 0x802305E0u, 0u, 0u, 0x8031A6E8u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0x8015EA5Cu, 0u, 0u, 0u, 0u, 0u,
    0u, 0x8030FADCu, 0u, 0x8031DC9Cu, 0x8031F45Cu, 0x800A0B60u, 0u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0u, 0x8031F348u, 0u, 0u, 0x8031D400u, 0u,
    0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u,
    0u, 0u, 0x80182A90u, 0x8030F5A4u, 0u, 0u, 0u, 0u,
    0x80328F84u, 0u, 0u, 0u, 0u, 0u, 0x8030F618u, 0x8015E3F0u,
    0x80181634u, 0x8031EF98u, 0x8031F93Cu, 0u, 0u, 0u, 0u, 0u,
    0x8031E8C4u, 0x80240744u, 0x8031F0E0u, 0x8031EC68u, 0u, 0u, 0u, 0u,
};

/* The key set the table is a permutation of, in ascending order.
 * A test asserts the lookup finds every one of these, which is the
 * check that catches a header whose table and hash parameters
 * disagree: a fast reject that answers false for a key the switches
 * would match is a boot failure, not a slowdown. */
static const u32 g_edge_keys_all[BLUEWAKE_EDGE_KEY_COUNT] = {
    0x80017FD8u, 0x800A0B60u, 0x800D8DB8u, 0x80120188u, 0x8015D80Cu, 0x8015E3F0u, 0x8015EA5Cu, 0x8017E798u,
    0x8017E86Cu, 0x80181634u, 0x80182A90u, 0x801DBA58u, 0x801DD960u, 0x8022F9FCu, 0x802305E0u, 0x80230A14u,
    0x802315A8u, 0x80240744u, 0x80240EE8u, 0x80241178u, 0x802411F8u, 0x80303A50u, 0x80308A9Cu, 0x8030F2B0u,
    0x8030F5A4u, 0x8030F618u, 0x8030FADCu, 0x8030FBCCu, 0x803193ACu, 0x8031A6E8u, 0x8031CD50u, 0x8031D2E0u,
    0x8031D400u, 0x8031D438u, 0x8031DAFCu, 0x8031DC9Cu, 0x8031DD80u, 0x8031E5C8u, 0x8031E74Cu, 0x8031E8C4u,
    0x8031EA48u, 0x8031EC68u, 0x8031EF98u, 0x8031F0E0u, 0x8031F348u, 0x8031F45Cu, 0x8031F69Cu, 0x8031F7C8u,
    0x8031F93Cu, 0x8031F984u, 0x80322BC8u, 0x80328F84u, 0x81E000D4u, 0x81E01B88u, 0x81E01BA4u,
};

/* Probe until the address is found or an empty slot ends the chain. */
static inline bool bluewake_edge_maybe_intercept(u32 address) {
    u32 slot = (address * BLUEWAKE_EDGE_KEY_MULT) >>
               BLUEWAKE_EDGE_KEY_SHIFT;
    for (;;) {
        const u32 key = g_edge_keys[slot];
        if (key == address)
            return true;
        if (key == 0u)
            return false;
        slot = (slot + 1u) % BLUEWAKE_EDGE_KEY_SLOTS;
    }
}

#endif
