# Exercise the pinned runtime's real worker-start decision without a GPU.
set(_fifo_source "${GXRUNTIME_DIR}/backends/aurora/aurora_graphics.cpp")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_fifo_source}")
file(READ "${_fifo_source}" _fifo_text)
string(FIND "${_fifo_text}" "void g_fifo_worker_start() {" _fifo_start)
string(FIND "${_fifo_text}" "// Stops the translation worker" _fifo_end)
if(_fifo_start LESS 0 OR _fifo_end LESS _fifo_start)
    message(FATAL_ERROR "Could not locate the production FIFO worker start decision")
endif()
math(EXPR _fifo_length "${_fifo_end} - ${_fifo_start}")
string(SUBSTRING "${_fifo_text}" ${_fifo_start} ${_fifo_length} _fifo_function)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/fifo_worker_start_under_test.inc" "${_fifo_function}")
find_package(Threads REQUIRED)
add_executable(bluewake_fifo_trace_worker_test "${BLUEWAKE_REPO_ROOT}/tests/fifo_trace_worker_test.cpp")
target_include_directories(bluewake_fifo_trace_worker_test PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
target_link_libraries(bluewake_fifo_trace_worker_test PRIVATE Threads::Threads)
add_test(NAME bluewake_fifo_trace_worker_test COMMAND bluewake_fifo_trace_worker_test)
set_tests_properties(bluewake_fifo_trace_worker_test PROPERTIES TIMEOUT 15)
