#!/usr/bin/env python3
"""Game options: settings a player switches at runtime (mods/betterww/options.txt).

An option changes the game three ways, none of which needs a patched disc:

  * sites: instructions DolRecomp translates both ways (--option-sites), picking
    one at run time by the option's switch; or places where the host's native
    code runs (runtime/host/src/game_options.c).
  * writes: values written into guest memory at boot while the option is on;
    a REL's are written at the REL's linked address, where its data lives for
    the whole session.

    game_options.py sites SPEC            the site list for dolrecomp --option-sites
    game_options.py check SPEC            parse and report

build_mod_variants.py --options SPEC --rels-bin-dir DIR adds the option table
and the writes to mod_variants.inc.
"""
import struct
import sys
from pathlib import Path

WRITE_TYPES = {"f32": ">f", "u32": ">I", "u16": ">H", "u8": ">B"}


class Spec:
    def __init__(self, path):
        self.options = []   # (index, name, default_on, title)
        self.sites = []     # (where, index, kind, value)
        self.writes = []    # (where, index, bytes)
        by_name = {}
        for number, raw in enumerate(Path(path).read_text().splitlines(), 1):
            line = raw.split("#", 1)[0].split()
            if not line:
                continue
            what = line[0]
            fail = lambda why: sys.exit("%s:%d: %s" % (path, number, why))
            if what == "option":
                if len(line) < 5 or line[3] not in ("on", "off"):
                    fail("expected `option NAME INDEX on|off TITLE`")
                name, index = line[1], int(line[2], 0)
                if not 1 <= index <= 255 or name in by_name or index in by_name.values():
                    fail("option %s: index %d taken or out of range" % (name, index))
                by_name[name] = index
                self.options.append((index, name, line[3] == "on", " ".join(line[4:])))
                continue
            if len(line) != 5 or line[2] not in by_name:
                fail("expected `%s WHERE OPTION KIND VALUE` with a declared option" % what)
            where, index, kind, value = line[1], by_name[line[2]], line[3], line[4]
            if what == "site" and kind in ("insn", "imm16"):
                self.sites.append((where, index, kind, int(value, 0)))
            elif what == "hook" and kind in ("before", "after"):
                self.sites.append((where, index, "hook" if kind == "before" else "after", int(value, 0)))
            elif what == "write" and kind in WRITE_TYPES:
                number_value = float(value) if kind == "f32" else int(value, 0)
                self.writes.append((where, index, struct.pack(WRITE_TYPES[kind], number_value)))
            else:
                fail("unknown %s kind %s" % (what, kind))
        wheres = [s[0] for s in self.sites]
        if len(wheres) != len(set(wheres)):
            sys.exit("%s: two sites at one address" % path)


def rel_sections(rel_path):
    """(module id, [(file offset, size)]) of a REL file."""
    data = Path(rel_path).read_bytes()
    be = lambda o: struct.unpack_from(">I", data, o)[0]
    count, table = be(0x0C), be(0x10)
    return be(0), [(be(table + 8 * i) & ~1, be(table + 8 * i + 4)) for i in range(count)]


def resolve_writes(spec, rels_bin_dir, rel_linked):
    """[(option index, guest address, bytes)]; rel_linked maps (module id,
    section) to the section's linked address (build_mod_variants.rel_data)."""
    out = []
    for where, index, data in spec.writes:
        if "+" not in where:
            out.append((index, int(where, 0), data))
            continue
        rel, offset = where.split("+")
        offset = int(offset, 0)
        module_id, sections = rel_sections(Path(rels_bin_dir) / rel)
        for section_index, (start, size) in enumerate(sections):
            if start and start <= offset and offset + len(data) <= start + size:
                linked = rel_linked.get((module_id, section_index))
                if linked is None:
                    sys.exit("%s: section %d has no linked data image" % (where, section_index))
                out.append((index, linked + offset - start, data))
                break
        else:
            sys.exit("%s is in no section of %s" % (where, rel))
    return out


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in ("sites", "check"):
        sys.exit(__doc__)
    spec = Spec(sys.argv[2])
    if sys.argv[1] == "sites":
        print("# Generated by scripts/mods/game_options.py from %s -- do not edit." % sys.argv[2])
        for where, index, kind, value in spec.sites:
            print("%s %d %s 0x%X" % (where, index, kind, value))
    else:
        print("%d options, %d sites, %d writes" % (len(spec.options), len(spec.sites), len(spec.writes)))


if __name__ == "__main__":
    main()
